language: c

env:
  global:
    - IDE_VERSION=1.8.5
   
before_install:
  - echo "Downloading version $IDE_VERSION of the Arduino IDE ..."
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz #Extracting Arduino IDE
  - sudo mv arduino-$IDE_VERSION "/usr/local/share/arduino"
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
#install:
# - arduino --pref "boardsmanager.additional.urls=https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json"

script:
  - "echo $HOME"
  - "ls $HOME"
  - "ls /usr/local"
  - "ls /usr/local/share"
  - "ls /usr/local/share/arduino"
  - "ls /usr/local/bin"
#  - "ls $PWD"
#- "echo $PWD"
#  - "ls $PWD"
  - "cd /usr/local/share/arduino"
  - "ls $PWD"
  -  arduino --verify --board arduino:avr:uno $PWD/examples/01.Basics/Blink/Blink.ino

notifications:
  email:
    on_success: change
    on_failure: change
